---

- name: install mysql repo
  yum:
    name: https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm
    state: present

- name: install mysql5.7
  yum:
    name: mysql
    state: present

- name: install mysql server
  yum:
    name: mysql-server
    state: present

- name: start mysql
  service:
    name: mysqld
    state: started
    enabled: yes
